import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[shell]
program = "/opt/homebrew/bin/fish"
args = ["-c", "tmux a || tmux"]

[env]
TERM = "xterm-256color"

[window]
padding = {x = 10, y = 10}
decorations = "Buttonless"
# opacity = 0.9
# blur = true

[scrolling]
history = 0

[font]
normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}
bold = {family = "JetBrainsMono Nerd Font", style = "Bold"}
italic = {family = "JetBrainsMono Nerd Font", style = "Italic"}
bold_italic = {family = "JetBrainsMono Nerd Font", style = "Bold Italic"}
size = 16

[font.offset]
x = 1
y = 1

[selection]
save_to_clipboard = true

[cursor.style]
blinking = "On"

[cursor.vi_mode_style]
blinking = "On"

[mouse]
hide_when_typing = true



